---
#<% require 'poise_boiler' %>
<%= PoiseBoiler.kitchen %>

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: centos-6.5
#- name: centos-7

chef_versions:
- 12

suites:
- name: default
  run_list:
  - recipe[poise-service_test]
- name: override
  run_list:
  - recipe[poise-service_test::override]
  attributes:
    poise-service:
      poise_test:
        provider: sysvinit
        template: "poise-service_test:override.sh.erb"
